version: 1.0.0.{build}
skip_tags: true
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(APPVEYOR_REPO_COMMIT)'
build:
  project: SqlMsBuildTasks.sln
  verbosity: minimal
after_build:
- cmd: nuget pack src\SqlMsBuildTasks.nuspec -version "%appveyor_build_version%"
- cmd: nuget pack src\SqlMsBuildTasks.symbols.nuspec -version "%appveyor_build_version%" -Symbols
- cmd: 7z a SqlMsBuildTasks-%appveyor_build_version%.zip license.txt
- cmd: cd src\SqlMsBuildTasks\bin\Release && 7z a ..\..\..\..\SqlMsBuildTasks-%appveyor_build_version%.zip SqlMsBuildTasks.*
artifacts:
- path: '*.zip'
- path: '*.nupkg'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true